output: main
extension: out

directories:
  src: [ src ] 
  obj: obj
  bin: bin
  include: [ include ]

ignore: []

flags:
  error_flags: -Wall -Wunused-variable -Wextra -Wno-enum-compare -g -ggdb -fdiagnostics-color=always
  windows_flags: -lgdi32 -lwinmm -static-libstdc++
  unix_flags: -lm -lpthread -ldl -lrt -lX11
  end_flags: -lyaml-cpp

compiler_version: g++
language_version: c++20

build_type: debug
