output: kole
extension: none 

directories:
  src: [ src ]
  obj: obj
  bin: bin
  include: [ include ]

exclude: []

flags:
  common: -Wall -Wunused-variable -Wextra -Wno-enum-compare -g -ggdb -fdiagnostics-color=always
  windows: -lgdi32 -lwinmm -static-libstdc++
  linux: -lm -lpthread -ldl -lrt -lX11 -lfmt -lyaml-cpp
  
compiler_version: g++
language_version: c++17

optimization: release