output: kole
extension: none

platform: auto

directories:
  src: [ src.qt ]
  ui: [ ui ]
  obj: obj
  bin: bin
  include: [ include.qt ]

exclude: []

flags:
  common: -Wall -Wunused-variable -Wextra -Wno-enum-compare -g -ggdb -fdiagnostics-color=always
  windows: -lgdi32 -lwinmm -static-libstdc++
  linux: -lm -lpthread -ldl -lrt -lX11 `pkg-config --cflags --libs Qt5Widgets`

qt_support:
  compile_ui: true
  compile_moc: true
  ui_prefix: ui_
  ui_extension: hpp
  ui_output_dir: ui
  moc_prefix: moc_

compiler_version: g++
language_version: c++17

optimization: release
